// 用户相关
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';

// 工时相关
export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_LIST_FAILURE = 'TASK_LIST_FAILURE';

export const TASK_DETAILS_REQUEST = 'TASK_DETAILS_REQUEST';
export const TASK_DETAILS_SUCCESS = 'TASK_DETAILS_SUCCESS';
export const TASK_DETAILS_FAILURE = 'TASK_DETAILS_FAILURE';

export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST';
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS';
export const TASK_CREATE_FAILURE = 'TASK_CREATE_FAILURE';

export const TASK_UPDATE_REQUEST = 'TASK_UPDATE_REQUEST';
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS';
export const TASK_UPDATE_FAILURE = 'TASK_UPDATE_FAILURE';

export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_FAILURE = 'TASK_DELETE_FAILURE';

export const LOG_WORK_REQUEST = 'LOG_WORK_REQUEST';
export const LOG_WORK_SUCCESS = 'LOG_WORK_SUCCESS';
export const LOG_WORK_FAILURE = 'LOG_WORK_FAILURE';

// 薪资相关
export const SALARY_LIST_REQUEST = 'SALARY_LIST_REQUEST';
export const SALARY_LIST_SUCCESS = 'SALARY_LIST_SUCCESS';
export const SALARY_LIST_FAILURE = 'SALARY_LIST_FAILURE';

export const SALARY_DETAILS_REQUEST = 'SALARY_DETAILS_REQUEST';
export const SALARY_DETAILS_SUCCESS = 'SALARY_DETAILS_SUCCESS';
export const SALARY_DETAILS_FAILURE = 'SALARY_DETAILS_FAILURE';

export const YEARLY_SALARY_REQUEST = 'YEARLY_SALARY_REQUEST';
export const YEARLY_SALARY_SUCCESS = 'YEARLY_SALARY_SUCCESS';
export const YEARLY_SALARY_FAILURE = 'YEARLY_SALARY_FAILURE';

// 考勤相关类型
export const ATTENDANCE_REQUEST = 'ATTENDANCE_REQUEST';
export const ATTENDANCE_SUCCESS = 'ATTENDANCE_SUCCESS';
export const ATTENDANCE_FAILURE = 'ATTENDANCE_FAILURE';

export const CLOCK_IN_REQUEST = 'CLOCK_IN_REQUEST';
export const CLOCK_IN_SUCCESS = 'CLOCK_IN_SUCCESS';
export const CLOCK_IN_FAILURE = 'CLOCK_IN_FAILURE';

export const CLOCK_OUT_REQUEST = 'CLOCK_OUT_REQUEST';
export const CLOCK_OUT_SUCCESS = 'CLOCK_OUT_SUCCESS';
export const CLOCK_OUT_FAILURE = 'CLOCK_OUT_FAILURE';

export const FETCH_ATTENDANCE_RECORD_REQUEST = 'FETCH_ATTENDANCE_RECORD_REQUEST';
export const FETCH_ATTENDANCE_RECORD_SUCCESS = 'FETCH_ATTENDANCE_RECORD_SUCCESS';
export const FETCH_ATTENDANCE_RECORD_FAILURE = 'FETCH_ATTENDANCE_RECORD_FAILURE';

export const FETCH_ATTENDANCE_STATS_REQUEST = 'FETCH_ATTENDANCE_STATS_REQUEST';
export const FETCH_ATTENDANCE_STATS_SUCCESS = 'FETCH_ATTENDANCE_STATS_SUCCESS';
export const FETCH_ATTENDANCE_STATS_FAILURE = 'FETCH_ATTENDANCE_STATS_FAILURE'; 